### ISSUE TITLE
tailor as a terraform provider

### ISSUE THREAD

**Issue by tbugfinder** [opendevstack/tailor#154]
I'm wondering if it could make sense building Tailor as a terraform provider.

**Comment by tbugfinder** [comment]
https://www.terraform.io/docs/extend/writing-custom-providers.html

**Comment by michaelsauter** [comment]
In theory possible I think. I even investigated that a little and then stopped it because parsing the config is crazy. Really crazy. Also, there is lots of nitty-gritty with OpenShift so not sure how easy it would be to accomplish that with Terraform. Further, Tailor integrates with OpenShift templates, which are easy to export from OpenShift - using Terraform config would require users to migrate their templates.

**Comment by michaelsauter** [comment]
I'm closing this as Tailor is not using Terraform by choice. As I said, building something like Tailor as a Terraform provider should be possible, but it would be a different product.
