### ISSUE TITLE
Support ad-hoc base64 encryption for Secrets 

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/tailor#44]
Currently you need to provide base64 encoded vars for usage in secrets- we should do Auto encoding- aß er know what goes into a secret.

**Comment by michaelsauter** [comment]
I would argue that secrets should be encrypted, and if encryption is used, then the base64-encoding happens automatically already. The whole secrets management is not ideal yet, so we'll definitely have to look for ways to improve the UX but I don't think adding this feature is necessary since it just bypasses what you should be doing: encrypting the secrets.
